# Site settings
title: "Dom McKellar"
header-img: img/home-bg.jpeg
email: dom.mckellar@gmail.com
copyright_name: "Dom McKellar"
description: > # this means to ignore newlines until "baseurl:"
  by Dom McKellar
baseurl: "" # the subpath of your site, e.g. /blog
author: "Dom McKellar"
twitter_username: _dom_mc
linkedin_username: dom-mckellar
github_username:  Dom-Mc
facebook_username: dom.mckellar
google-plus_username: DomMckellar
learn_profile: Dom-Mc
email_username: dom.mckellar@gmail.com
# site_name: "newme"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
